version: '3'
services:
  auth-service:
    container_name: auth-service
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/auth-service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_DEFAULT_ZONE=http://eureka-service:8761/eureka
    depends_on:
      - db
      - eureka-service
      - gateway-service

  field-service:
    container_name: field-service
    build:
      context: ./backend/field-service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/field-service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_DEFAULT_ZONE=http://eureka-service:8761/eureka
    depends_on:
      - db
      - eureka-service
      - gateway-service

  owner-service:
    container_name: owner-service
    build:
      context: ./backend/owner-service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/owner-service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_DEFAULT_ZONE=http://eureka-service:8761/eureka
    depends_on:
      - db
      - eureka-service
      - gateway-service

  payment-service:
    container_name: payment-service
    build:
      context: ./backend/payment-service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/payment-service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_DEFAULT_ZONE=http://eureka-service:8761/eureka
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - db
      - eureka-service
      - gateway-service
  
  db:
    container_name: db
    image: mysql:8
    volumes:
      - ./docker/db:/var/lib/mysql
      - ./docker/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8090:80'
    depends_on:
      - db

  gateway-service:
    container_name: gateway-service
    build:
      context: ./backend/gateway-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - EUREKA_DEFAULT_ZONE=http://eureka-service:8761/eureka
    depends_on:
      - eureka-service
  
  eureka-service:
    container_name: eureka-service
    build:
      context: ./backend/eureka-service
      dockerfile: Dockerfile
    ports:
      - 8761:8761

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.9
    hostname: zookeeper
    ports:
      - 2181:2181
    volumes:
      - ./docker/zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.6
    volumes:
      - ./docker/kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend/docker
      dockerfile: Dockerfile
    ports:
      - 8000:80
