version: '3'
services:
  db:
    container_name: tax-on-ul-db
    image: mysql:8
    volumes:
      - ./docker/db:/var/lib/mysql
      - ./docker/initdb:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
  phpmyadmin:
    container_name: tax-on-ul-phpmyadmin
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '9000:80'
    depends_on:
      - db

  zookeeper:
    container_name: tax-on-ul-zookeeper
    image: bitnami/zookeeper:3.9
    hostname: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: tax-on-ul-kafka
    image: bitnami/kafka:3.6
    ports:
      - 9094:9094
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    depends_on:
      - zookeeper
  
  frontend:
    container_name: tax-on-ul-frontend
    build:
      context: ./frontend/docker
      dockerfile: Dockerfile.dev
      args:
        USER: ${USER}
        UID: ${UID}
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 80:4200
