version: '3'
services:
  auth-service:
    container_name: auth-service
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://auth-db:3306/auth-service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_DEFAULT_ZONE=http://eureka-service:8761/eureka
    depends_on:
      - auth-db
      - eureka-service
      - gateway-service
  auth-db:
    container_name: auth-db
    image: mysql:8
    volumes:
      - ./docker/auth_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: auth-service
  auth-phpmyadmin:
    container_name: auth-phpmyadmin
    image: phpmyadmin:latest
    environment:
      PMA_HOST: auth-db
      PMA_PORT: 3306
    ports:
      - '8090:80'
    depends_on:
      - auth-db

  field-service:
    container_name: field-service
    build:
      context: ./backend/field-service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://field-db:3306/field-service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_DEFAULT_ZONE=http://eureka-service:8761/eureka
    depends_on:
      - field-db
      - eureka-service
      - gateway-service
  field-db:
    container_name: field-db
    image: mysql:8
    volumes:
      - ./docker/field_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: field-service

  owner-service:
    container_name: owner-service
    build:
      context: ./backend/owner-service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://owner-db:3306/owner-service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_DEFAULT_ZONE=http://eureka-service:8761/eureka
    depends_on:
      - owner-db
      - eureka-service
      - gateway-service
  owner-db:
    container_name: owner-db
    image: mysql:8
    volumes:
      - ./docker/owner_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: owner-service

  payment-service:
    container_name: payment-service
    build:
      context: ./backend/payment-service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://payment-db:3306/payment-service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - EUREKA_DEFAULT_ZONE=http://eureka-service:8761/eureka
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - payment-db
      - eureka-service
      - gateway-service
  payment-db:
    container_name: payment-db
    image: mysql:8
    volumes:
      - ./docker/payment_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: payment-service

  gateway-service:
    container_name: gateway-service
    build:
      context: ./backend/gateway-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - EUREKA_DEFAULT_ZONE=http://eureka-service:8761/eureka
  
  eureka-service:
    container_name: eureka-service
    build:
      context: ./backend/eureka-service
      dockerfile: Dockerfile
    ports:
      - 8761:8761

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.9
    hostname: zookeeper
    ports:
      - 2181:2181
    volumes:
      - ./docker/zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.6
    ports:
      - 9094:9094
    volumes:
      - ./docker/kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    depends_on:
      - zookeeper
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8000:80
