server:
  port: 0
spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/auth-service
    username: root
    password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret: te2hC58cNwiTCR8W7c9kQfiXjwOYAiLf
  expiration: 86400
