server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret: te2hC58cNwiTCR8W7c9kQfiXjwOYAiLf
