server:
  port: 0
spring:
  application:
    name: field-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/field-service
    username: root
    password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
