server:
  port: 0
spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/payment-service
    username: root
    password:
  kafka:
    bootstrap-servers: localhost:9094
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
